### ISSUE TITLE
Iterate example doesn't include iterate method

### ISSUE THREAD

**Issue by cw00dw0rd** [arangodb/docs#1119]
https://github.com/arangodb/docs/blob/main/3.10/data-modeling-documents-document-methods.md#misc

I think the code snippet shown is supposed to be wrapped in the `iterate` method call, but not sure.

**Comment by Simran-B** [comment]
The example is truly broken forever, and so is the iterate method (both added in January 2013):

https://github.com/arangodb/arangodb/commit/9c87607f461a34e20fd1c62123e107f166b58e3a#diff-4f14e2f5e1736e5f8bf3770cc8016435ce6f00e72a71b895cb8dba2ff5b60c99R206-R292

- The example uses the map method instead of showing how to use the iterate method
- The logic for probability is flawed. Higher values make it less likely to pick a document unless the probability is >= 1.0
- Any calls of the method with a probability < 1.0 result in an error because `db` is undefined. It seems like `require("@arangodb").db` isn't available in common modules

**Comment by Simran-B** [comment]
After checking with Jan, `iterate()` will be deprecated from 3.11 onwards and potentially be removed in 4.0 because it's hardly useful and only works with small collections (it loads the entire collection content).

**Comment by Simran-B** [comment]
Documentation updates added to #1144
