### ISSUE TITLE
Mac Homebrew Install Location changed for M1 & M2 models

### ISSUE THREAD

**Issue by kvdmolen** [arangodb/docs#1264]
Installing ArangoDB using **homebrew** on a Mac **M1** or **M2** is located in another folder.
Seems the correct way to start the server is:
`$ /opt/homebrew/Cellar/arangodb/3.10.3/sbin/arangod &`
Docs should be updated ;)

**Comment by Simran-B** [comment]
Thanks for the report. Unfortunately, we no longer support homebrew because the maintainers insist on using specific compiler versions and options that are untested with our product and potentially incompatible, as well as of other long-standing limitations of homebrew. I opened a pull request to remove leftover mentions of brew from the 3.10+ documentation, but I added a note to the 3.9 docs that you may find arangod in a different location.
