### ISSUE TITLE
No mention of orphanCollections in HTTP docs for creating a graph

### ISSUE THREAD

**Issue by DiscoPYF** [arangodb/docs#280]
The documentation for the HTTP endpoint `POST /_api/gharial` does not mention anything about the property `orphanCollections` that can be used inside the JSON content of the request.

https://www.arangodb.com/docs/stable/http/gharial-management.html#create-a-graph

I see this happening on 3.5 and 3.4.

This property should be documented because it can be used to specify the orphan collections of the Graph when it is created.

Example:

A request `POST /_api/gharial` with the following JSON content:

```json
{
	"name": "myTestGraph",
	"orphanCollections": ["myclx"]
}
```

Gives the following result:

```json
{
    "error": false,
    "code": 202,
    "graph": {
        "_key": "myTestGraph",
        "numberOfShards": 1,
        "replicationFactor": 1,
        "isSmart": false,
        "edgeDefinitions": [],
        "orphanCollections": [
            "myclx"
        ],
        "_rev": "_Zzwfq_e--_",
        "_id": "_graphs/myTestGraph",
        "name": "myTestGraph"
    }
}
```

The current documentation:

![image](https://user-images.githubusercontent.com/8124146/71626436-12bb6e80-2be5-11ea-8e49-8c75bca6f509.png)

The documentation should be updated to add the `orphanCollections` property to the JSON object of the request.

**Comment by Simran-B** [comment]
Well spotted. Thanks for the letting us know @DiscoPYF. I created a PR for 3.6 to test the changes:
https://github.com/arangodb/arangodb/pull/10807

**Comment by DiscoPYF** [comment]
@Simran-B Thank you for creating that PR.
What about the previous doc versions? Have they been left out on purpose?

Also, I tried to verify this issue but the doc for 3.6 still doesn't mention `orphanCollections`. Could you share with me what the process is to close an issue? I couldn't find anything mentioned in the contributing guide.

**Comment by Simran-B** [comment]
As the change needs to be made to a DocuBlock, a separate PR for each version branch in the main repository is necessary. I haven't cherry-picked the changes yet.

Because it's a DocuBlock, it is necessary to re-generate the example files (and along with it the allComments.txt, which is currently used to exchange Swagger information with Jekyll). I'm waiting for the next bugfix release (3.5.4) to do that. This is part of the deployment process, which is only documented internally. We have Jenkins jobs for example generation, documentation building and upload, but it needs to be deployed to the live environment of our hoster manually. That is why we don't update the online docs that often.

**Comment by Simran-B** [comment]
Added to 3.4 and above, docs republished.
