### ISSUE TITLE
Possibly older versions indexed in search engines

### ISSUE THREAD

**Issue by x3cion** [arangodb/docs#40]
Search engines seem to grab random versions of the docs. It would be nice if the version indexed would always be stable instead.

Examples:
https://www.google.com/search?q=arangodb+aql
https://www.google.com/search?q=arangodb+foxx
https://www.google.com/search?q=arangodb+satellite+collections

This might come with other implications, like duplicate content.

**Comment by dothebart** [comment]
Hi, 
these can be workarounded by using the google `site:` keyword:
https://www.google.com/search?q=satelite+collections+site%3Aarangodb.com%2Fdocs%2F3.4%2F
(with this plain content in the search dialog: `satelite collections site:arangodb.com/docs/3.4/`)

Since there are also users of older ArangoDB versions around (that want in fact want to have documentation the older ArangoDB versions they're actually using)  this is a problem not easy to address with the current feature set google offers.

**Comment by Simran-B** [comment]
We moved the docs to a new server recently, and will take the old docs 2.8..3.2 offline soon. We will then also request a removal of the old URLs from Google. The pages under the new address define the stable version as canonical and should therefore show up first. It will just take a couple of weeks.
