### ISSUE TITLE
Atomicity is not clear enough

### ISSUE THREAD

**Issue by alex-novikov-1990** [arangodb/docs#739]
https://www.arangodb.com/docs/stable/aql/operations-upsert.html#limitations
> The lookup and the insert/update/replace parts are executed non-atomically.

https://www.arangodb.com/docs/stable/data-modeling-operational-factors.html#operation-atomicity
> Using a single instance of ArangoDB, multi-document / multi-collection queries are guaranteed to be fully ACID

Probably, the last should be about "reads", not "queries".

**Comment by neunhoef** [comment]
I am not entirely sure what to do here. 

The first issue seems to be about upsert and the sentence about "non-atomically". What is the question here? In the manual, directly after this sentence there are more explanations. Is there anything wrong with these explanations?

The second is about the word "queries" as opposed to "reads". I think "queries" is actually meant here, since writes are definitely a part of the business here. If only reads would be involved, then the term ACID does not really make sense. So again, I do not really know what to do.

On the other hand, the explanations in these sections are far from optimal. After all, it is not really clear which version of "ACID" we mean and the term is probably in itself a bit outdated.

What shall we do here? Or should we do anything?

**Comment by alex-novikov-1990** [comment]
@neunhoef, thank you for the answer. The issue was about the inconsistency between the quotations: the first states that upsert queries are not atomic, but the second states that all queries are atomic in a single instance scenario. Therefore, it is impossible to understand from the documentation, whether upserts into single instance ArangoDB are atomic.

**Comment by neunhoef** [comment]
I see. I think the confusion is about the word "atomic" in two different contexts. 

In the first citation, the word "non-atomic" refers to the two operations needed for an UPSERT, the read and the update. It is possible, that if two UPSERTS Upsert1 and Upsert2 run concurrently, the 4 operations are executed in the order Read1, Read2, Update1, Update2 and thus Update2 runs into a conflict and cannot proceed.

The second citation is only about writes and talks about "atomicity" for single writes. What is indeed true even in the above scenario is that each of the operations Update1 and Update2 are in itself atomic, in the sense that any other operation observes either all of a change or nothing at all. In all of ArangoDB, a change to a single document is always atomic in this sense.

I think this should indeed be clarified, although both statements are in a sense correct as they stand. My suggestion would be to replace the word "non-atomically" in the first citation by something else. The exact meaning is well-described in the sentence afterwards, so this should then be OK. We only want to avoid the word "atomic" here.

The second citation should see a larger change, in particular since the term "ACID" was never really well defined and has fallen out of fashion. How about this version for the paragraph:

"
All insert / update / replace / remove operations in ArangoDB are atomic on a single document, by which we mean that any read operation either observes a single document write in its entirety or not at all, regardless of whether it is a read in the same transaction, a different transaction, or indeed another write operation implicitly reading the document (like update). This is true in cluster mode as well as in single server mode and for one shard databases.

Using a single instance of ArangoDB (or a one shard database), multi-document / multi-collection queries are guaranteed to be fully atomic, in the sense that one transaction observes any other transaction either in its entirety, or not at all. In these cases, the isolation level ArangoDB guarantees for transactions is "repeatable read" in the following sense: the reads of a transaction see a snapshot of the state of the database, that is, a transaction T does not see "dirty reads" from other transactions which have not yet committed. Furthermore, in the end, there is a total order on the set of all transactions, such that the state of the database is as if the writes of the transactions would have been executed in this order.

Note that this is strictly weaker than "serializable", since it is possible that two concurrent transactions T1 and T2 both read the old state from before both of them (including the documents T1 or T2 touch), but then write to disjoint sets of keys. This allows for the possibility of "phantom reads".

The reason for this behaviour is that we use RocksDB's snapshot isolation and pessimistic key level locking to implement ArangoDB transactions.
"

**Comment by Simran-B** [comment]
Documentation adjusted: #875
