### ISSUE TITLE
Results code for errors are not complete

### ISSUE THREAD

**Issue by fceller** [arangodb/docs#94]
https://www.arangodb.com/docs/devel/http/collection-creating.html

- 404 seems wrong
- what is the error code in case of leader change during creation?
- what is the error code in case of duplicate names?

**Comment by Simran-B** [comment]
> 404: If the collection-name is unknown, then a HTTP 404 is returned.

Not sure what _unknown_ is supposed to mean in this context, it seems to belong to another HTTP method (`GET .../_api/collection/{name}` -> **404** collection or view not found)

Empty POST body as well as invalid collection name leads to **404** illegal name. The **400** missing name error can not be triggered it seems...

Conflict with existing collection leads to **409** duplicate name

Docs look outdated but also partially broken?

**Comment by Simran-B** [comment]
Recent changes to error codes:
* Changed HTTP return code for an error case in /_api/cluster/endpoints REST API.
  Now, if the API is called on a single server, it will return HTTP 501 instead
  of HTTP 403 (https://github.com/arangodb/arangodb/pull/10743/files ?)
* Changed HTTP return code for an error case in /_api/cluster/agency-dump REST API.
  Now, if the API is called on a server type other than coordinator, it will return 
  HTTP 501 instead of HTTP 403.
* The General Graph document API is now consistent with the document API in its error messages.
  When attempting to create / modify edges pointing to non existing vertex collections
  HTTP 400 is returned instead of 404.
* more?
